version: "3.8"

services:
  frontend:
    image: node:14
    container_name: frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: ["npm", "run", "dev"]
    depends_on:
      - backend

  backend:
    image: node:14
    container_name: backend
    working_dir: /app
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "5000:5000"
    command: ["npm", "start"]
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/mydatabase
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

volumes:
  postgres_data:
